sudo: required

dist: trusty

language: python

python:
  - '2.7'

before_install:
  - sudo -H apt-get install -qq -y python-matplotlib
  - sudo -H apt-get install -qq -y python-nose
  - sudo -H apt-get install -qq -y python-numpy
  - sudo -H apt-get install -qq -y python-qt4
  - sudo -H apt-get install -qq -y pyqt4-dev-tools
  - sudo -H apt-get install -qq -y python-scipy
  - sudo -H apt-get install -qq -y python-skimage
  # - pip install flake8 hacking
  # - flake8 .

install:
  - sudo -H python setup.py install

script:
  - sudo -H pip install matplotlib  # FIXME
  - nosetests tests
