sudo: required

dist: trusty

language: python

python:
  - '2.7'

before_install:
  - sudo -H apt-get install python-matplotlib
  - sudo -H apt-get install python-numpy
  - sudo -H apt-get install python-qt4
  - sudo -H apt-get install pyqt4-dev-tools
  - sudo -H apt-get install python-scipy
  - sudo -H apt-get install python-skimage
  # - pip install flake8 hacking
  # - flake8 .

install:
  - sudo -H python setup.py install

script:
  - sudo -H pip install nose
  - nosetests tests
