sudo: required

dist: trusty

language: generic

before_install:
  - sudo -H apt-get install -qq -y libpython2.7-dev
  - sudo -H apt-get install -qq -y python-minimal
  - sudo -H apt-get install -qq -y python-tk

install:
  - sudo -H apt-get install -qq -y pyqt4-dev-tools
  - sudo -H apt-get install -qq -y python-qt4
  - sudo -H pip install -U pip setuptools
  - sudo -H python setup.py install

script:
  - sudo -H apt-get install -qq -y python-nose
  - nosetests tests
