language: generic
sudo: required
dist: trusty

env:
  global:
    # used by ci-helpers
    - SETUP_XVFB=true PIP_DEPENDENCIES='hacking pytest pytest-qt'
  matrix:
    - PYTEST_QT_API=pyqt4v2 PYQT_PACKAGE='pyqt=4' PYTHON_VERSION=2.7.14
    - PYTEST_QT_API=pyside2 CONDA_CHANNELS='conda-forge' PYQT_PACKAGE='pyside2' PYTHON_VERSION=2.7.14
    - PYTEST_QT_API=pyside2 CONDA_CHANNELS='conda-forge' PYQT_PACKAGE='pyside2' PYTHON_VERSION=3.6.5
    - PYTEST_QT_API=pyqt5 PYQT_PACKAGE='pyqt=5' PYTHON_VERSION=2.7.14
    - PYTEST_QT_API=pyqt5 PYQT_PACKAGE='pyqt=5' PYTHON_VERSION=3.6.5

install:
  - sudo apt-get update

  # Xvfb / window manager
  - sudo apt-get install -y xvfb herbstluftwm

  # Setup miniconda
  - git clone --depth 1 git://github.com/astropy/ci-helpers.git
  - export __PATH__=$PATH
  - export __PYTHONPATH__=$PYTHONPATH
  - CONDA_DEPENDENCIES=$PYQT_PACKAGE source ci-helpers/travis/setup_conda.sh
  - source activate test && pip install .

before_script:
 - "herbstluftwm &"
 - sleep 1

script:
  - source activate test
  - flake8 examples labelme setup.py tests
  - pytest -v tests
  - labelme --help
  - labelme --version
  - (cd examples/tutorial && rm -rf apc2016_obj3_json && labelme_json_to_dataset apc2016_obj3.json && python load_label_png.py && git checkout -- .)
  - (cd examples/semantic_segmentation && rm -rf data_dataset_voc && ./labelme2voc.py labels.txt data_annotated data_dataset_voc && git checkout -- .)
  - (cd examples/instance_segmentation && rm -rf data_dataset_voc && ./labelme2voc.py labels.txt data_annotated data_dataset_voc && git checkout -- .)

after_script:
  - |
    if [ $PYTHON_VERSION = "3.6.5" -a $PYQT_PACKAGE = "pyqt=5" ]; then
      # Cleanup
      export PATH=$__PATH__
      export PYTHONPATH=$__PYTHONPATH__

      # Setup pyenv
      git clone https://github.com/pyenv/pyenv.git $HOME/.pyenv
      export PYENV_ROOT=$HOME/.pyenv
      export PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
      pyenv install -ks $PYTHON_VERSION
      pyenv global $PYTHON_VERSION
      which python && python --version
      which pip && pip --version

      # Build the standalone executable
      pip install .
      pip uninstall -y matplotlib
      pip install pyinstaller
      pyinstaller labelme.spec
      dist/labelme --version
    fi

branches:
  only:
    - master

notifications:
  email: false
